# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse.xci
# IP: The module: 'Clk_HPulse' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_HPulse'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_HPulse'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_HPulse'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse.xci
# IP: The module: 'Clk_HPulse' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_HPulse'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_HPulse'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Piete/OneDrive/Bureaublad/School/2-BasisDigitaleElektronica/Projecten/Pong/Pong.srcs/sources_1/ip/Clk_HPulse/Clk_HPulse_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_HPulse'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
